const crypto = require("crypto"); // crypto is inbuilt module of node.
// const crypto = require("node:crypto"); // other way of writing.
console.log("Namaste World!");

var a = 1022222;
var b = 89999933;

// password based key derivative function : pbkdf

// Sync function : blocked thread. it will make everyone wait. NEVER USE THEM
crypto.pbkdf2Sync("password", "salt", 5000000, 50, "sha512");
// this will never have a callback, as it not resolved by the libuv and nothing there is their to get a callback.
console.log("Key is generated by Synchronous.");


setTimeout(() => {
  console.log("Call me right now ASAP!");
}, 0); // it will wait and only called after the callstack is empty and as here we have a sync function so it wil work only after sync function and the multiplication.


// Async function
crypto.pbkdf2("password", "salt", 5000000, 50, "sha512", (err, key) => {
  console.log("Key is generated by Asynchronous");
});

function multiply(a, b) {
  const result = a * b;
  return result;
}

var c = multiply(a, b);
console.log("Multiplication of two numbers is " + c);
